<a href="https://colab.research.google.com/github/vasimakramsy/titanic_with_RandomForrest/blob/master/Titanic_with_RandomForr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
%cd drive

/content/drive


In [3]:
%cd My Drive

/content/drive/My Drive


In [4]:
!ls

'c1 class 1 Exercise.txt'
'Colab Notebooks'
'convalutional neural network document.gdoc'
'Copy of dogs-vs-cats-train-validadion-and-evaluation.zip'
'Deep learning .gdoc'
 dogs-vs-cats-train-validadion-and-evaluation
 fruit_cnn_model_1.h5
'How to get started with Drive.pdf'
'Linear Regression Part - 2 .ipynb'
 LinearSearch.py
 __MACOSX
 Project_ImageClassification_report.gdoc
 Resume.gdoc


In [5]:
%cd ..


/content/drive


In [6]:
%cd ..

/content


In [8]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: train.csv               
  inflating: test.csv                
  inflating: gender_submission.csv   


In [0]:
import pandas as pd
import numpy as np


In [0]:
data_raw = pd.read_csv('train.csv')

In [17]:
data_raw.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [18]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


## now after checking the info the first an dmost importent work we have to do is to convert all the object data type to numbers 

In [0]:
'''now am writing a function to convert the object dtype'''
def assigning_categorical(data, column):
    categories = []
    for i in data[column].unique():
        categories.append(i)
    try:    
        categories.remove(np.nan)
    except Exception as e:
        pass
    data[column+'_new'] = pd.Categorical(data[column], categories=categories, ordered=True).codes
    data.drop(f'{column}', axis=1, inplace = True)
    data.replace(-1, np.nan, inplace=True)

In [0]:
# lets check its working
assigning_categorical(data_raw,'Name')

In [22]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
Name_new       891 non-null int16
dtypes: float64(2), int16(1), int64(5), object(4)
memory usage: 78.4+ KB


In [0]:
# its working and we dont need Name column because it has to much of unique value as same as dataset
# hence it will create lot of variations drop it

data_raw.drop('Name_new',axis=1,inplace=True)

In [0]:
'''lets try to do automation'''

for columns in data_raw.columns:
  if data_raw[columns].dtype=='O':
    assigning_categorical(data_raw,columns)

In [25]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
PassengerId     891 non-null int64
Survived        891 non-null int64
Pclass          891 non-null int64
Age             714 non-null float64
SibSp           891 non-null int64
Parch           891 non-null int64
Fare            891 non-null float64
Sex_new         891 non-null int8
Ticket_new      891 non-null int16
Cabin_new       204 non-null float64
Embarked_new    889 non-null float64
dtypes: float64(4), int16(1), int64(5), int8(1)
memory usage: 65.3 KB


In [26]:
'''every thing worked fine now lets check the null values in the dataset'''

data_raw.isna().sum()/(len(data_raw))

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Age             0.198653
SibSp           0.000000
Parch           0.000000
Fare            0.000000
Sex_new         0.000000
Ticket_new      0.000000
Cabin_new       0.771044
Embarked_new    0.002245
dtype: float64

In [0]:
'''lets do automation to fill this nullvalue'''

for i in data_raw.columns:
  data_raw[i] = data_raw[i].fillna(data_raw[i].median())

In [28]:
data_raw.isna().sum()

PassengerId     0
Survived        0
Pclass          0
Age             0
SibSp           0
Parch           0
Fare            0
Sex_new         0
Ticket_new      0
Cabin_new       0
Embarked_new    0
dtype: int64

In [0]:
'''seperate the dataset'''
X=data_raw.drop('Survived',axis=1)
y=data_raw['Survived']

In [0]:
'''import the model'''
from sklearn.ensemble import RandomForestClassifier
forr_1=RandomForestClassifier()

In [34]:
forr_1.fit(X,y)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
forr_1.score(X,y)

0.9865319865319865

## without adding any parameter i have created an model forr_1 its now over fitting now lets create with considering parameters

In [0]:
'''by default parameter n_estimators are 10 lets try to add more and check'''

forr_2=RandomForestClassifier(n_estimators=20)

In [37]:
forr_2.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [39]:
forr_2.score(X,y)

0.9966329966329966

In [0]:
'''by increasing n_estimators by 20 its increse in over fitting lets increase little more'''

forr_2=RandomForestClassifier(n_estimators=40)

In [45]:
forr_2.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [46]:
forr_2.score(X,y)

0.9977553310886644

In [0]:
'''by increasing the n_estimators its not changeing anything so lets 
try with changing deapth and branch of tree
'''
forr_3=RandomForestClassifier(n_estimators=40,max_depth=3,max_leaf_nodes=3)

In [50]:
forr_3.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features='auto', max_leaf_nodes=3,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [51]:
forr_3.score(X,y)

0.7912457912457912

In [0]:
'''actully now the model is performing better then previous lets try to add more'''

forr_4=RandomForestClassifier(n_estimators=40,max_depth=5,max_leaf_nodes=5)

In [53]:
forr_4.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [54]:
forr_4.score(X,y)

0.8125701459034792

In [0]:
'''changing the max_depth,max_leaf its not affecting lets try with other parameters'''
forr_4=RandomForestClassifier(n_estimators=40,max_depth=3,max_leaf_nodes=3,max_features=10)

In [63]:
forr_4.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features=10, max_leaf_nodes=3,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [64]:
forr_4.score(X,y)

0.7867564534231201

In [0]:
'''adding max_features the overfitting decreasing . 
Adding more actully increased the fitting so i tried decreasing at certain point its reduced 
so am fixing max_features at 4'''

forr_4=RandomForestClassifier(n_estimators=40,max_depth=3,max_leaf_nodes=3,max_features=4)

In [88]:
forr_4.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=3, max_features=4, max_leaf_nodes=3,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=40,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [89]:
forr_4.score(X,y)

0.7744107744107744

In [0]:
from sklearn.model_selection import cross_val_score

In [93]:
'''now lets check all model cross validation score'''

print('Model one without parameters only by default')

cross_val_score(forr_1,X,y,cv=3)



Model one without parameters only by default


array([0.77441077, 0.73400673, 0.7979798 ])

In [94]:
print('model with increased trees')
cross_val_score(forr_2,X,y,cv=3)


model with increased trees


array([0.8013468 , 0.78114478, 0.80808081])

In [95]:
print('model with adding depth and leaf')
cross_val_score(forr_3,X,y,cv=3)





model with adding depth and leaf


array([0.75084175, 0.82154882, 0.77104377])

In [96]:
print('model with adding max_feature parameter')

cross_val_score(forr_4,X,y,cv=3)

model with adding max_feature parameter


array([0.75420875, 0.8013468 , 0.79124579])

hence after looking at all the cross validation score the model with parameters geting around 80% good accuracy